//! SVG icon golden (#57): rasterize a bundled icon at a target px through `Renderer::icon_coord` (resvg
//! → RGBA atlas), then render it as a `PolychromeSprite` — proving the SVG → atlas → render path. The
//! icon is monochrome white, drawn with an identity (white) tint, so it shows as a white checkmark.
//!
//! Reference is canonical to Mesa lavapipe (the CI `golden` job); on a non-canonical adapter (local DX12
//! WARP) the pixel compare is skipped. The reference is generated by the `golden-update` workflow before
//! the PR is opened (the new `/pr` Step 5.5), so CI is green on the first run.

use kagari_base::{Color, Corners, Rect};
use kagari_render::{IconId, PolychromeSprite, RoundedRect, Scene};

#[test]
fn icon_check_should_match_golden() {
    let rendered = kagari_golden::headless_render_with((48, 48), 1.0, |renderer| {
        // Rasterize the check icon at 32px into the RGBA atlas (synchronous, glyph-style).
        let coord = renderer.icon_coord(IconId::Check, 32);

        let no_clip = RoundedRect {
            rect: Rect::from_xywh(0.0, 0.0, 1.0e4, 1.0e4),
            radii: Corners::default(),
        };
        let mut scene = Scene::new();
        scene.images.push(PolychromeSprite {
            bounds: Rect::from_xywh(8.0, 8.0, 32.0, 32.0),
            tex: coord,
            tint: Color::new(1.0, 1.0, 1.0, 1.0), // identity → white icon
            content_mask: no_clip,
            order: 0,
        });
        scene
    });

    let Some(r) = rendered else {
        eprintln!("skipping golden 'icon_check': no software adapter available");
        return;
    };
    if !r.canonical {
        eprintln!(
            "skipping golden compare 'icon_check': non-canonical rasterizer (goldens are lavapipe-canonical)"
        );
        return;
    }
    kagari_golden::assert_golden!("icon_check", r.image);
}
