//! Icon element golden (#246): render deferred [`IconSprite`] requests at **two sizes** through the
//! renderer's resolve step (`scene.icons` → rasterize at `bounds.h × scale` → tinted `PolychromeSprite`).
//! This exercises the composable-element path (the element pushes requests; the renderer resolves them),
//! distinct from `icon_golden` (which calls `Renderer::icon_coord` directly).
//!
//! Reference is canonical to Mesa lavapipe (the CI `golden` job); on a non-canonical adapter (local DX12
//! WARP) the pixel compare is skipped. The reference is generated by the `golden-update` workflow before
//! the PR is opened (`/pr` Step 5.5), so CI is green on the first run.

use kagari_base::{Color, Corners, Rect};
use kagari_render::{IconId, IconSprite, RoundedRect, Scene};

#[test]
fn icon_element_two_sizes_should_match_golden() {
    let rendered = kagari_golden::headless_render_with((64, 64), 1.0, |_renderer| {
        let no_clip = RoundedRect {
            rect: Rect::from_xywh(0.0, 0.0, 1.0e4, 1.0e4),
            radii: Corners::default(),
        };
        let white = Color::new(1.0, 1.0, 1.0, 1.0);
        let mut scene = Scene::new();
        // Two deferred requests at different sizes — the renderer rasterizes each at its physical size
        // (`bounds.h × scale`) into the RGBA atlas, then draws the tinted image sprite.
        scene.icons.push(IconSprite {
            bounds: Rect::from_xywh(4.0, 4.0, 16.0, 16.0),
            icon: IconId::Check,
            tint: white,
            content_mask: no_clip,
            order: 0,
        });
        scene.icons.push(IconSprite {
            bounds: Rect::from_xywh(24.0, 24.0, 32.0, 32.0),
            icon: IconId::ChevronDown,
            tint: white,
            content_mask: no_clip,
            order: 1,
        });
        scene
    });

    let Some(r) = rendered else {
        eprintln!("skipping golden 'icon_element_two_sizes': no software adapter available");
        return;
    };
    if !r.canonical {
        eprintln!(
            "skipping golden compare 'icon_element_two_sizes': non-canonical rasterizer (goldens are lavapipe-canonical)"
        );
        return;
    }
    kagari_golden::assert_golden!("icon_element_two_sizes", r.image);
}
