//! Path primitive golden (#58): tessellate a filled shape and a stroked polyline via `PathBuilder` and
//! render them with feathered AA, proving the path pipeline (tessellation → vertex/index buffers →
//! feather coverage × content-mask) end to end.
//!
//! Reference is canonical to Mesa lavapipe (the CI `golden` job); on a non-canonical adapter (local DX12
//! WARP) the pixel compare is skipped. References are generated by the `golden-update` workflow before
//! the PR (the `/pr` Step 5.5), so CI is green on the first run.

use kagari_base::{Color, Corners, Point, Rect};
use kagari_render::{PathBuilder, RoundedRect, Scene};

fn no_clip() -> RoundedRect {
    RoundedRect {
        rect: Rect::from_xywh(0.0, 0.0, 1.0e4, 1.0e4),
        radii: Corners::default(),
    }
}

/// White (opaque premultiplied) so the shape is visible on the dark clear.
fn white() -> Color {
    Color::new(1.0, 1.0, 1.0, 1.0)
}

#[test]
fn path_fill_should_render_with_aa() {
    let rendered = kagari_golden::headless_render_with((48, 48), 1.0, |_renderer| {
        // A filled triangle.
        let mut b = PathBuilder::new();
        b.move_to(Point::new(24.0, 8.0))
            .line_to(Point::new(40.0, 40.0))
            .line_to(Point::new(8.0, 40.0))
            .close();
        let mut scene = Scene::new();
        scene.paths.push(b.fill(white(), no_clip(), 0));
        scene
    });

    let Some(r) = rendered else {
        eprintln!("skipping golden 'path_fill': no software adapter available");
        return;
    };
    if !r.canonical {
        eprintln!(
            "skipping golden compare 'path_fill': non-canonical rasterizer (goldens are lavapipe-canonical)"
        );
        return;
    }
    kagari_golden::assert_golden!("path_fill", r.image);
}

#[test]
fn path_stroke_should_render_with_aa() {
    let rendered = kagari_golden::headless_render_with((48, 48), 1.0, |_renderer| {
        // A stroked zig-zag polyline (a waveform-like shape).
        let mut b = PathBuilder::new();
        b.move_to(Point::new(6.0, 30.0))
            .line_to(Point::new(18.0, 14.0))
            .line_to(Point::new(30.0, 34.0))
            .line_to(Point::new(42.0, 16.0));
        let mut scene = Scene::new();
        scene.paths.push(b.stroke(3.0, white(), no_clip(), 0));
        scene
    });

    let Some(r) = rendered else {
        eprintln!("skipping golden 'path_stroke': no software adapter available");
        return;
    };
    if !r.canonical {
        eprintln!(
            "skipping golden compare 'path_stroke': non-canonical rasterizer (goldens are lavapipe-canonical)"
        );
        return;
    }
    kagari_golden::assert_golden!("path_stroke", r.image);
}
